### PR TITLE
Fix uses in tests

### PR DESCRIPTION
**Pull request by isomethane**
I changed ClassOrObjectUses class in new branch, so I needed to change tests for it.
I also changed ReflektUsesTestModel file so that now we can compare expected and actual uses with assertEquals. What do you think about it?

### CODE REVIEW

**Comment by nbirillo** [comment]
Sorry, could you please merge the `develop` branch into your branch? Because some changes here are from the `develop` branch. It would be easier to review then it

**Comment by isomethane** [comment]
Oh yes, sorry for this.

**Review by nbirillo — CHANGES_REQUESTED** [review]
This looks great, but let's change a base branch to the `develop` branch and push the current branch into the `develop`?

**Comment by isomethane** [comment]
This branch contains large merge commits with logics and code from base branch so I created another branch for this purpose.

**Pull request closed without merging**
